apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "overops-reset-cache.fullname" . }}
  labels:
    {{- include "overops-reset-cache.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": post-install,post-upgrade
spec:
  template:
    metadata:
      labels:
        {{- include "overops-reset-cache.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      restartPolicy: Never
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["redis-cli"]
          args: ["-h", "$(CACHE_HOST)", "-p", "$(CACHE_PORT)", "FLUSHALL"]
          env:
            - name: CACHE_HOST
              value: {{ .Values.cache.host | quote }}
            - name: CACHE_PORT
              value: {{ .Values.cache.port | quote }}

      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
