# Default values for overops-reset-cache.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

cache:
  host: ''
  port: 6379

image:
  repository: redis
  pullPolicy: IfNotPresent
  tag: "6.2-alpine"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

podSecurityContext: {}
securityContext: {}
nodeSelector: {}
affinity: {}
