apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "overops-server.fullname" . }}-config
  labels:
    {{- include "overops-server.labels" . | nindent 4 }}
data:
  my.server.properties: |-
  {{- if .Values.overops.defaultUserEnabled }}
    LOCAL_DEFAULT_USER_JSON=  {"email": {{ .Values.overops.defaultUser | quote }}, "password": "${DEFAULT_PASS}", "first_name": {{ .Values.overops.defaultUserFirst | quote }}, "last_name": {{ .Values.overops.defaultUserLast | quote }}}
    LOCAL_DEFAULT_USER_SERVICE_SECRET_KEY= ${DEFAULT_SERVICE_KEY}
    LOCAL_GENERATE_FIRST_USER_SERVICE_AND_LABELS=true
  {{- end }}

{{- if .Values.config.enableExtraConfig }}
{{- range $key, $val := .Values.config.myServerProperties }}
{{ $val | indent 4}}
{{- end }}

{{- range $key, $val := .Values.config.extraConfigurationFiles }}
  {{ $key }}: |-
{{ $val | indent 4}}
{{- end }}
{{- end -}}
