{{- if not .Values.overops.auth.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "overops-server.fullname" . }}
  labels:
    {{- include "overops-server.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.overops.defaultUserPass  }}
  default-user-password:  {{ .Values.overops.defaultUserPass | b64enc | quote }}
  {{ end }}
  {{- if .Values.externalDatabase.dbPassword  }}
  db-password:  {{ .Values.externalDatabase.dbPassword | b64enc | quote }}
  {{ end }}
  {{- if .Values.overops.rabbitQueue.enabled  }}
  rmq-password:  {{ .Values.overops.rabbitQueue.password | b64enc | quote }}  
  {{ end }}  
{{- end }}