{{- if not .Values.auth.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "overops-server.fullname" . }}
  labels:
    {{- include "overops-server.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.externalDatabase.dbPassword  }}
  dbPassword:  {{ .Values.externalDatabase.dbPassword | b64enc | quote }}
  {{ end }}
  {{- if .Values.overops.defaultUserPass  }}
  defaultUserPass:  {{ .Values.overops.defaultUserPass | b64enc | quote }}
  {{ end }}
  {{- if .Values.overops.defaultUserServiceKey  }}
  defaultUserServiceKey:  {{ .Values.overops.defaultUserServiceKey| b64enc | quote }}
  {{ end }}
{{- end }}