{{- if not .Values.overops.auth.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "overops-receiver-server.fullname" . }}
  labels:
    {{- include "overops-receiver-server.labels" . | nindent 4 }}
type: Opaque
data:
  db-password:  {{ .Values.overops.mysql.password | b64enc | quote }}
  rmq-password:  {{ .Values.overops.rabbitQueue.password | b64enc | quote }}
  host: {{ (printf "amqp://%s:%s@%s:%s/" .Values.overops.rabbitQueue.username ( .Values.overops.rabbitQueue.password | urlquery ) .Values.overops.rabbitQueue.service ( .Values.overops.rabbitQueue.port | toString )) | b64enc }}
{{- end }}